language: go
go:
- 1.8
- 1.7
- 1.6.3
- 1.6.2
env:
  global:
  - GOARCH=amd64
  - GO_FOR_RELEASE=1.8
script:
- go test
after_success:
- go build
notifications:
  email:
    on_success: change
    on_failure: always
